            
<ScreenManager>:
    
    HomeScreen:
    ShumScreen:
<HomeScreen>:
    name: "Home"
    BoxLayout:
        orientation: "horizontal"
       
        Image:
            source: './public/shumHIMSELF.png'
            size: self.texture_size
        BoxLayout:
            orientation: "vertical"
            Label:
                text: "What would you like to know about Shum?"
            Button:
                text: "Who is Shum?"
                on_press: root.change_screen()
            Button:
                text: "What is the Church of Shum?"
                on_press: root.change_screen()
            

<ShumScreen>
    name: "WhoIsShum"
    BoxLayout:
        orientation: "horizontal"
        Button:
            text: "Shum is the man"
            on_press: root.change_screen()