            
<ScreenManager>:
    HomeScreen:
    ShumScreen:

<HomeScreen>:
            

<ShumScreen>
    name: "ShumScreen"
    BoxLayout:
        orientation: "horizontal"
        
        Button:
            id: the_button
            text: ""
            on_press: root.change_screen()
            halign: 'center'
            valign: 'middle'
            color: 0, 0, 0, 1
            background_color: 0, 0, 0, 0
            
            font_size: '18sp' 
            
            text_size: self.size
            padding: [10,2,10,2]
            